### ISSUE TITLE
build error if not executing tests: Could not parse certificate: java.io.IOException: Empty input

### ISSUE THREAD

**Issue by j75** [ammbra/micrometering-with-quarkus#4]
With GraalVM :
```
java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
```
Then
```
mvn package -Pnative -Dmaven.test.skip

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.7.1.Final:build (default) on project micrometering-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep#process threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:103)
[ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:97)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:214)
[ERROR] 	at io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory.createHttpClient(OkHttpClientFactory.java:89)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:164)
[ERROR] 	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:48)
[ERROR] 	at io.fabric8.kubernetes.client.BaseKubernetesClient.<init>(BaseKubernetesClient.java:159)
[ERROR] 	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:42)
[ERROR] 	at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createClient(KubernetesClientUtils.java:50)
[ERROR] 	at io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep.process(KubernetesClientBuildStep.java:16)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
[ERROR] 	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:115)
[ERROR] 	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355)
[ERROR] 	at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:98)
[ERROR] 	at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:74)
[ERROR] 	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:140)
[ERROR] 	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:90)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:203)
[ERROR] 	... 18 more
[ERROR] Caused by: java.io.IOException: Empty input
[ERROR] 	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:111)
[ERROR] 	... 24 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by j75** [comment]
Without `-Dmaven.test.skip` the result is different:
```
% mvn package -Pnative
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< org.acme:micrometering-with-quarkus >-----------------
[INFO] Building micrometering-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ micrometering-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- quarkus-maven-plugin:2.7.1.Final:generate-code (default) @ micrometering-with-quarkus ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ micrometering-with-quarkus ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:2.7.1.Final:generate-code-tests (default) @ micrometering-with-quarkus ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ micrometering-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/OODRIVEGROUP/m.ion/Projets/Git/Marian/micrometering-with-quarkus/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ micrometering-with-quarkus ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ micrometering-with-quarkus ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.endpoint.ExampleEndpointTest
2022-03-23 17:16:12,292 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
17:16:13 WARN  traceId=, spanId=, sampled= [io.qu.mi.de.bi.mp.MicroprofileMetricsProcessor] (build-98) This application uses the MP Metrics API. The micrometer extension currently provides a compatibility layer that supports the MP Metrics API, but metric names and recorded values will be different. Note that the MP Metrics compatibility layer will move to a different extension in the future.
17:16:15 INFO  traceId=, spanId=, sampled= [io.ag.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
Hibernate: 
    
    drop table if exists Message CASCADE 
Hibernate: 
    
    drop sequence if exists message_id_seq
Hibernate: create sequence message_id_seq start with 1 increment by 1
Hibernate: 
    
    create table Message (
       id bigint not null,
        content varchar(255),
        locale varchar(255) not null,
        primary key (id)
    )
Hibernate: 
    INSERT INTO message (id, content, locale) VALUES (1000, 'bonjour','fr')
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 4, Time elapsed: 5.091 s <<< FAILURE! - in org.acme.endpoint.ExampleEndpointTest
[ERROR] org.acme.endpoint.ExampleEndpointTest.findNonExistingLanguage  Time elapsed: 0.007 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Unable to start HTTP server
Caused by: java.util.concurrent.ExecutionException: io.quarkus.runtime.QuarkusBindException
Caused by: io.quarkus.runtime.QuarkusBindException
...
INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ExampleEndpointTest.findNonExistingLanguage » Runtime java.lang.RuntimeExcepti...
[INFO] 
```

**Comment by ammbra** [comment]
Hi, 

Please read the following guide to find out more about packaging to native:https://quarkus.io/guides/building-native-image
You used a version of the GraalVM version that is not supported by the version of Quarkus used in the project (2.7.1 Final). In the guide, it is detailed that at least version 21.3.1 is needed, and also please pay attention to how to run the native build to produce the expected result. I would recommend looking more into the guide. 

Hope this helps you :)
